AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'bin/setup'
    - 'bin/update'

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false
